### ISSUE TITLE
Index template

### ISSUE THREAD

**Issue by halfempty** [once-future/commonedge#12]
@nikkichung I've begun styling the "index" template, from the example of the Suggested Reading area of the comps. Here's a link:

http://commonedge.staging.wpengine.com/

**Comment by nikkichung** [comment]
Wonderful! You're ahead of us. I've got landing page in-progress... Do you
want me to send you what we have so far as reference?

**Comment by nikkichung** [comment]
@halfempty Here's some feedback on the Index template so far. 

### General
- [ ] Could you try an image aspect ratio like 1:1.6 so images are less tall?

### 1024px
- [ ] Can we set a maximum width for the images? (We're not confident the client will be sourcing attractive images until they can hire a photo editor, so would like to keep images a bit smaller. Something around here: 

![screenshot 2015-12-08 22 54 04](https://cloud.githubusercontent.com/assets/15950066/11736369/6173980c-9f9b-11e5-93a9-bc4dbd632113.png)

### 768px
- [ ] Once author byline starts running into date, could we move the byline to be flush-left? Alternately, can we wrap the text of the author byline so the names stack rather than running under the date?

**Current**

![img_1183](https://cloud.githubusercontent.com/assets/15950066/11736424/382b6da2-9f9c-11e5-8b90-f8c2829fef97.jpg)

**Preferred**

![screenshot 2015-12-11 00 19 02](https://cloud.githubusercontent.com/assets/15950066/11736472/d5d82b6c-9f9c-11e5-9801-dd99ece9cb86.png)

or

![screenshot 2015-12-11 00 19 10](https://cloud.githubusercontent.com/assets/15950066/11736477/da6d0d6e-9f9c-11e5-8a5b-bc0cfb7d1bb7.png)

### 480px
- [ ] Once author byline starts running into date, could we move the byline to be flush-left? Alternately, can we wrap the text of the author byline so the names stack rather than running under the date?

### 320px
- [ ] Once author byline starts running into date, could we move the byline to be flush-left? Alternately, can we wrap the text of the author byline so the names stack rather than running under the date?

**Comment by nikkichung** [comment]
@halfempty Design for the top portion of the template for things like search results, filtered posts by tag, and search is in. Files are in Dropbox here: https://www.dropbox.com/sh/jvtqajha51u480z/AABnWA7fzjApHcn9HtbIblcfa?dl=0
