### ISSUE TITLE
Hamburger icon not loading

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#62]
hey @halfempty, 

Hamburger nav icone isn't loading for us on [mobile](https://www.dropbox.com/s/etltoxqczu2n5so/IMG_0621.PNG?dl=0) (Safari and Chrome). Can you take a look?

**Comment by halfempty** [comment]
@nikkichung Hi! How are you?

Yes, what's happened here is that we were loading a font for that icon, via a plugin. That plugin has updated and no longer loads that icon in that way. (The bigger picture is that over the years icon fonts have become deprecated, as has the SVG font format. The plugin update is likely a reflection of those trends.)

The thing to do, probably, is refactor it so that we're not using that font anymore, and are loading the icons as individual SVGs.

**Comment by nikkichung** [comment]
@halfempty Ahh ok cool, thanks. Shall we send you an SVG of a hamburger, or do you have one handy that might do the trick?

**Comment by halfempty** [comment]
@nikkichung ok, done

**Comment by nikkichung** [comment]
Thanks very much!
