### ISSUE TITLE
Breakpoint Styling

### ISSUE THREAD

**Issue by halfempty** [once-future/commonedge#9]
@nikkichung I've put in some styles at the 480px breakpoint. Would you like to take a look before I move up to the next one?

**Comment by nikkichung** [comment]
Sure, taking a look now.

**Comment by nikkichung** [comment]
@halfempty Looking really nice. A few requests:

### Global
- [x] Text sizes still reading a bit small, particularly Body, Dates, Bylines, Share, Tags, Footer h4. Could you size up another 1–2px?
- [x] Image caption could use a bit more top-padding (top margin?)
- [x] Possible to increase the space between the Footer h4 and it's border-bottom? Spacing feels a little tight. 

##### Q&A
- [x] Indenting alignment is just slightly off at beginning of question:

![img_8422](https://cloud.githubusercontent.com/assets/15950066/11603037/de8f72dc-9aac-11e5-8a25-6de99299590b.PNG)

**Comment by halfempty** [comment]
@nikkichung A bit more styling is in, applying to the largest sizes.

**Comment by nikkichung** [comment]
Fab!
http://once-future.com

**Comment by nikkichung** [comment]
Will follow up with feedback http://once-future.com

**Comment by nikkichung** [comment]
@halfempty Feedback is in. Overall the client is really happy with how it's coming together. So are we!

### 1024px
- [ ] Line-height of the body text is a bit tight. In Chrome, 1.58em feels pretty good.

**Current:**
![screenshot 2015-12-08 22 13 08](https://cloud.githubusercontent.com/assets/15950066/11735924/1a9d93e8-9f95-11e5-9c53-57a90acdf55f.png)

**Preferred:** 
![screenshot 2015-12-08 22 26 54](https://cloud.githubusercontent.com/assets/15950066/11735932/4990a3d4-9f95-11e5-925a-f04a21989d3b.png)
- [ ] Could you wrap the title at a shorter column width than the rule?
- [ ] Please increase distance between main content and footer.

![screenshot 2015-12-08 23 49 06](https://cloud.githubusercontent.com/assets/15950066/11735958/80133ce6-9f95-11e5-891f-f3a1af86cf98.png)

##### Tags, Author Bio
- [ ] lay out horizontally rather than vertical stack to keep those rules from being so long.
  ![screenshot 2015-12-08 22 46 53](https://cloud.githubusercontent.com/assets/15950066/11735957/7a21d84c-9f95-11e5-8a7a-9554fa405d2d.png)
- [ ] Increase margin/padding between these sections

### 768px
- [ ] The rules at the footer—Share This Story, Tags—should match the length of the rule above the byline.
- [ ] Please increase distance between main content and footer
